var missionNames = {
      0: "Initial",
      1: "Intro",
      2: "An Old Friend",
      3: "The Party",
      4: "Back Alley Brawl",
      5: "Jury Fury",
      6: "Riot",
      7: "Treacherous Swine",
      8: "Mall Shootout",
      9: "Guardian Angels",
      10: "Sir, Yes Sir!",
      11: "All Hands On Deck!",
      12: "The Chase",
      13: "Phnom Penh '86",
      14: "The Fastest Boat",
      15: "Supply & Demand",
      16: "Rub Out",
      17: "Death Row",
      18: "Four Iron",
      19: "Demolition Man",
      20: "Two Bit Hit",
      21: "No Escape?",
      22: "The Shootist",
      23: "The Driver",
      24: "The Job",
      25: "Gun Runner",
      26: "Boomshine Saigon",
      27: "Recruitment Drive",
      28: "Dildo Dodo",
      29: "Martha's Mug Shot",
      30: "G-spotlight",
      31: "Shakedown",
      32: "Bar Brawl",
      33: "Cop Land",
      34: "Spilling the Beans",
      35: "Hit the Courier",
      36: "Printworks Buy",
      37: "Sunshine Autos",
      38: "Interglobal Films Buy",
      39: "Cherry Popper Icecreams Buy",
      40: "Kaufman Cabs Buy",
      41: "Malibu Club Buy",
      42: "The Boatyard Buy",
      43: "Pole Position Club Buy",
      44: "El Swanko Casa Buy",
      45: "Links View Apartment Buy",
      46: "Hyman Condo Buy",
      47: "Ocean Heights Apt. Buy",
      48: "1102 Washington Street Buy",
      49: "Vice Point Buy",
      50: "Skumole Shack Buy",
      51: "Cap the Collector",
      52: "Keep your Friends Close...",
      53: "Alloy Wheels of Steel",
      54: "Messing with the Man",
      55: "Hog Tied",
      56: "Stunt Boat Challenge",
      57: "Cannon Fodder",
      58: "Naval Engagement",
      59: "Trojan Voodoo",
      60: "Juju Scramble",
      61: "Bombs Away!",
      62: "Dirty Lickin's",
      63: "Love Juice",
      64: "Psycho Killer",
      65: "Publicity Tour",
      66: "Weapon Range",
      67: "Road Kill",
      68: "Waste the Wife",
      69: "Autocide",
      70: "Check Out at the Check In",
      71: "Loose Ends",
      72: "V.I.P.",
      73: "Friendly Rivalry",
      74: "Cabmaggedon",
      75: "TAXI DRIVER",
      76: "PARAMEDIC",
      77: "FIREFIGHTER",
      78: "VIGILANTE",
      79: "HOTRING",
      80: "BLOODRING",
      81: "DIRTRING",
      82: "Sunshine Autos Races",
      83: "Distribution",
      84: "Downtown Chopper Checkpoint",
      85: "Ocean Beach Chopper Checkpoint",
      86: "Vice Point Chopper Checkpoint",
      87: "Little Haiti Chopper Checkpoint",
      88: "Trial by Dirt",
      89: "Test Track",
      90: "PCJ Playground",
      91: "Cone Crazy",
      92: "PIZZA BOY",
      93: "RC Raider Pickup",
      94: "RC Bandit Race",
      95: "RC Baron Race",
      96: "Checkpoint Charlie",
};

addNetworkHandler("missionStart", function (client, missionId) {
      if (client && client.player) {
            inMission.set(client.player.name, true);
            var name = missionNames[missionId] || "Unknown (" + missionId + ")";
            console.log("\x1b[32m[@MISSION]\x1b[0m " + client.player.name + " started mission " + missionId + " (" + name + ")");
      }
});

addNetworkHandler("missionEnd", function (client) {
      if (client && client.player) {
            inMission.set(client.player.name, false);
            console.log("\x1b[32m[@MISSION]\x1b[0m " + client.player.name + " ended mission");
      }
});
