const missionsToGet = {
      AVERY: [
            { toFinish: 6, id: 18 },
            { toFinish: 18, id: 19 },
            { toFinish: 13, id: 20 },
            { toFinish: 26, id: -1 },
      ],
      BIKERS: [
            { toFinish: 64, id: 53 },
            { toFinish: 53, id: 54 },
            { toFinish: 54, id: 55 },
            { toFinish: 55, id: 65 },
            { toFinish: 26, id: -1 },
      ],
      CORTEZ: [
            { toFinish: 6, id: 7 },
            { toFinish: 7, id: 8 },
            { toFinish: 8, id: 9 },
            { toFinish: 9, id: 10 },
            { toFinish: 10, id: 11 },
            { toFinish: 26, id: -1 },
      ],
      CUBANS: [
            { toFinish: 20, id: 56 },
            { toFinish: 56, id: 57 },
            { toFinish: 56, id: 60 },
            { toFinish: 60, id: 61 },
            { toFinish: 61, id: 62 },
            { toFinish: 57, id: 58 },
            { toFinish: 62, id: 59 },
            { toFinish: 26, id: -1 },
      ],
      DIAZ: [
            { toFinish: 11, id: 12 },
            { toFinish: 12, id: 13 },
            { toFinish: 13, id: 14 },
            { toFinish: 14, id: 15 },
            { toFinish: 17, id: 16 },
            { toFinish: 26, id: -1 },
      ],
      FILM: [
            { toFinish: 38, id: 27 },
            { toFinish: 27, id: 28 },
            { toFinish: 28, id: 29 },
            { toFinish: 29, id: 30 },
            { toFinish: 26, id: -1 },
      ],
      HAITIANS: [
            { toFinish: 56, id: 60 },
            { toFinish: 60, id: 61 },
            { toFinish: 61, id: 62 },
            { toFinish: 26, id: -1 },
      ],
      KCABS: [
            { toFinish: 40, id: 72 },
            { toFinish: 72, id: 73 },
            { toFinish: 73, id: 74 },
            { toFinish: 26, id: -1 },
      ],
      KENT: [{ toFinish: 15, id: 17 }],
      LAWYER: [
            { toFinish: -1, id: 3 },
            { toFinish: 3, id: 4 },
            { toFinish: 4, id: 5 },
            { toFinish: 5, id: 6 },
            { toFinish: 26, id: -1 },
      ],
      LOVEFIST: [
            { toFinish: 16, id: 63 },
            { toFinish: 63, id: 64 },
            { toFinish: 26, id: -1 },
      ],
      MALIBUCLUB: [
            { toFinish: 41, id: 21 },
            { toFinish: 21, id: 22 },
            { toFinish: 22, id: 23 },
            { toFinish: 23, id: 24 },
            { toFinish: 26, id: -1 },
      ],
      PHIL: [
            { toFinish: 24, id: 25 },
            { toFinish: 25, id: 26 },
            { toFinish: 26, id: -1 },
      ],
      PHONE: [{ toFinish: 5, id: 67 }],
      PHONEFIVE: [{ toFinish: 16, id: 70 }],
      PHONEFOUR: [{ toFinish: 70, id: 71, require: [22] }],
      PHONEONE: [{ toFinish: 14, id: 69 }],
      PHONETWO: [{ toFinish: 67, id: 68 }],
      PRINTWORKS: [
            { toFinish: 30, id: 34 },
            { toFinish: 34, id: 35 },
            { toFinish: 26, id: -1 },
      ],
      TOMMY: [
            { toFinish: 16, id: 32 },
            { toFinish: 24, id: 52 },
            { toFinish: 26, id: -1 },
      ],
      TOMMYTHREE: [{ toFinish: 32, id: 33 }],
};
